# Generated by Django 5.1 on 2024-09-16 09:50

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.AutoField)),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(verbose_name='desc')),
            ],
        ),
    ]
