# Generated by Django 5.1 on 2024-09-16 10:01

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=django.db.models.fields.BigAutoField),
        ),
    ]
