# Generated by Django 5.1 on 2024-09-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='default Description')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'Shoe',
            },
        ),
        migrations.CreateModel(
            name='ShoeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoe')),
            ],
            options={
                'db_table': 'ShoeStyle',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=7)),
                ('type', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('shoe', models.ManyToManyField(through='products.ShoeStyle', to='products.shoe')),
            ],
            options={
                'db_table': 'Style',
                'unique_together': {('color', 'size', 'material')},
            },
        ),
        migrations.AddField(
            model_name='shoestyle',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.style'),
        ),
        migrations.AlterUniqueTogether(
            name='shoestyle',
            unique_together={('shoe', 'style')},
        ),
    ]
