# Generated by Django 5.1 on 2024-10-28 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='HsnCode',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_code', models.BigIntegerField(null=True, verbose_name='Item Code')),
                ('item_name', models.TextField(null=True, verbose_name='Item Name')),
                ('item_type', models.TextField(null=True, verbose_name='Item Type')),
                ('GSTe', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='GST %e')),
                ('hsn_code', models.BigIntegerField(null=True, verbose_name='HSN Code')),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='GST %')),
            ],
            options={
                'db_table': 'products_hsncode',
            },
        ),
        migrations.CreateModel(
            name='ShoeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Shoe_Category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_inclusive', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(default='default Description')),
                ('gst_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('hsn_code', models.CharField(default=None, max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(default='\\products\\p7.jpg', upload_to='products/')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'Shoe',
            },
        ),
        migrations.CreateModel(
            name='ShoeCategoryShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoe')),
                ('shoecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoecategory')),
            ],
            options={
                'db_table': 'Shoe_Category_shoe',
                'unique_together': {('shoe', 'shoecategory')},
            },
        ),
        migrations.AddField(
            model_name='shoecategory',
            name='shoe',
            field=models.ManyToManyField(through='products.ShoeCategoryShoe', to='products.shoe'),
        ),
        migrations.CreateModel(
            name='ShoeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.shoe')),
            ],
            options={
                'db_table': 'ShoeStyle',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=7)),
                ('type', models.CharField(max_length=20)),
                ('material', models.CharField(max_length=20)),
                ('shoe', models.ManyToManyField(through='products.ShoeStyle', to='products.shoe')),
            ],
            options={
                'db_table': 'Style',
                'unique_together': {('color', 'size', 'material')},
            },
        ),
        migrations.AddField(
            model_name='shoestyle',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.style'),
        ),
        migrations.AlterUniqueTogether(
            name='shoestyle',
            unique_together={('shoe', 'style')},
        ),
    ]
