# Generated by Django 5.1 on 2024-09-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HsnCode',
            fields=[
                ('index', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_code', models.BigIntegerField(verbose_name='Item Code')),
                ('item_name', models.TextField(verbose_name='Item Name')),
                ('item_type', models.TextField(verbose_name='Item Type')),
                ('GSTe', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %e')),
                ('hsn_code', models.BigIntegerField(verbose_name='HSN Code')),
                ('GST', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='GST %')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_inclusive',
        ),
        migrations.AddField(
            model_name='product',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
