# Generated by Django 5.1 on 2024-10-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_hsncode_gst_alter_hsncode_gste_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hsncode',
            table='hsn_code',
        ),
    ]
