# Generated by Django 5.1 on 2024-10-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_shoecategoryshoe_alter_shoecategory_shoe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoecategoryshoe',
            old_name='category',
            new_name='shoecategory',
        ),
        migrations.AlterUniqueTogether(
            name='shoecategoryshoe',
            unique_together={('shoe', 'shoecategory')},
        ),
    ]
