# Generated by Django 5.1 on 2024-10-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_address_alter_order_order_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
